### ISSUE TITLE
example.yml has elements defined that are not recognised by the plugin

### ISSUE THREAD

**Issue by dfch** [boundary/boundary-vmware#32]
When you use the example.yml to monitor a vCenter and try to start the jar as described in the README, you will receive an error at startup and the process will be terminated.

There are at least two entries in the example.yml that are not recognised by the plugin

* `meterManagerClient`
* `orgId`

The excerpt of the example.yml in the README does not contain the aforementioned entities

Please correct the `example.yml`

# error messages on startup

    [boundary@cmbound-lab1ch ~]$ java -jar boundary-vmware/target/vmware-metrics-collector-1.0.0.jar server cmvc.yml
	cmvc-lab1ch.mgmt.sccloudpoc.net.yml has an error:
	  * Unrecognized field at: meterManagerClient
	    Did you mean?:
	      - metricsClient
	      - metrics
	      - client
	      - server
	      - monitoredEntities
	        [1 more]

	*all meterManagerClient stuff was commented*

	[boundary@cmbound-lab1ch ~]$ java -jar boundary-vmware/target/vmware-metrics-collector-1.0.0.jar server cmvc.yml
	cmvc-lab1ch.mgmt.sccloudpoc.net.yml has an error:
	  * Unrecognized field at: orgId
	    Did you mean?:
	      - server
	      - logging
	      - metrics
	      - client
	      - metricsClient
	        [1 more]

**Comment by jdgwartney** [comment]
example.yml has been updated to remove the offending fields along with the additional information in the README
