### ISSUE TITLE
Plugin does not start when vCenter has no public or trusted certificate

### ISSUE THREAD

**Issue by dfch** [boundary/boundary-vmware#33]
When trying to start the plugin via `java -jar target/vmware-metrics-collector-1.0.0.jar server cmvc.yml` we receive the following error message and the plugin does not start:

    Causing: javax.net.ssl.SSLHandshakeException: 
    sun.security.validator.ValidatorException: PKIX path building failed:
    sun.security.provider.certpath.SunCertPathBuilderException: 
    unable to find valid certification path to requested target

**Comment by dfch** [comment]
any update on this? with this blocking issue in place the plugin is not usable at all

**Comment by jdgwartney** [comment]
I was given this endpoint uri: https://172.17.19.100/sdk/vimService and I do not have the issue. Are you using the same endpoint?

**Comment by jdgwartney** [comment]
Can you update the configuration and turn on full debugging "level: DEBUG" and provide the output.

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG
  # Logger-specific levels.
  loggers:
    # Overrides the level of com.example.dw.<package name or class> 
    # and sets it to DEBUG.
    #"org.apache.http.wire": DEBUG
    com.boundary: INFO

**Comment by dfch** [comment]
@jdgwartney we are testing this against our own installation/lab, so we are probably not using the same vCenter instance. I will do the tests and update you. thanks!

**Comment by valerioj** [comment]
we are maybe using the same vCenter instance to test, but now we describe it in the conf files with the FQDN, and not with the IP address anymore. That might be a problem. Should we copy some certificate somewhere? what's the procedure if we want to monitor a new vCenter instance?

**Comment by valerioj** [comment]
here's the log, Dave

**Comment by valerioj** [comment]
logs were sent through email, cause i tried to attach the file here and it didn't work.

**Comment by jdgwartney** [comment]
Submitted a fix that returns zero length array for Trusted Certificates, rather than null. I have been only able to test against the instance 172.17.19.100 which did not exhibit the error.

**Comment by valerioj** [comment]
this bug does not appear anymore, the collector is still not functioning correctly, but i consider that this issue is fixed. thanks

**Comment by dfch** [comment]
closing the issue
