### ISSUE TITLE
example.yml: use of target field is not described

### ISSUE THREAD

**Issue by dfch** [boundary/boundary-vmware#34]
There is a `target` field within the `example.yml` that is not described, i.e. it is not clear which value this field must have in order to configure the plugin.

**Comment by jdgwartney** [comment]
README has been updated with better description of the fields in the example.yml. There is not a target field but a field called name that has a value of target in the example.yml

**Comment by jdgwartney** [comment]
Latest pull request resolves this issue

**Comment by dfch** [comment]
thx!
